---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: https://github.com/adonisgarciac/gitops-operators.git
      revision: main
      directories:
        #- path: operators/loki-operator
        - path: operators-installer
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/adonisgarciac/gitops-operators.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions: []
...
