---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: gitops-1.11
  installPlanApproval: Manual
  name: openshift-gitops-operator
  source: redhat-operators-index
  sourceNamespace: openshift-marketplace
...