---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-operators-redhat-approver-rb
  namespace: openshift-operators-redhat
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-operators-redhat-approver-role
subjects:
  - kind: ServiceAccount
    name: openshift-operators-redhat-approver-sa
...