---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-operators-redhat-approver-sa
  namespace: openshift-operators-redhat
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
...