---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: openshift-operators-redhat
spec:
  channel: stable-5.8
  installPlanApproval: Manual
  name: loki-operator
  source: redhat-operator
  sourceNamespace: openshift-marketplace
  startingCSV: loki-operator.v5.8.0
...